services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: myload-balancer
    depends_on:
      - express
    environment:
      - NGINX_SERVER_NAME=localhost
      - EXPRESS_HOST_1=first-express-2
     # - EXPRESS_HOST_2=first-express-2
     # - EXPRESS_HOST_3=first-express-3
      # - EXPRESS_HOST_4=first-express-4
      # - EXPRESS_HOST_5=first-express-5
      - EXPRESS_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 3000:3000
  express:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./index.js:/app/index.js
      - .env:/app/.env
      - ./uploads:/app/uploads
    
    scale: 1
    depends_on:
      - mongodb
      - redis
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    container_name: mymongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
  redis:
    image: redis:5
    container_name: mycadt-redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:cadt-redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
volumes:
  mongodbdata: