version: "1.1"
name: Status Check
env:
  host: localhost:3000
tests:
  example:
    steps:
      - name: Health Check
        http:
          url: http://${{env.host}}/health-check
          method: GET
          check:
            status: /^20/